# Generated by Django 5.0.1 on 2024-01-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("modifiedDate", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("tag", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("content", models.CharField(max_length=100)),
                ("contain", models.BooleanField(verbose_name="계산시 포함 여부")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
