# Generated by Django 5.0.1 on 2024-01-30 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("modifiedDate", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=63)),
                ("balance", models.IntegerField(default=0)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "costmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.costmodel",
                    ),
                ),
                (
                    "bankAccountId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenditure.bankaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.costmodel",),
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "costmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.costmodel",
                    ),
                ),
                (
                    "bankAccountId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenditure.bankaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.costmodel",),
        ),
    ]
